server {
    listen 8080;

    location / {
        default_type application/json;
        return 200 '{"headers": {"X-User-Id": "$http_x_user_id", "X-User-Name": "$http_x_user_name", "X-User-Email": "$http_x_user_email", "X-User-Roles": "$http_x_user_roles"}}';
    }
}
