debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.database.hostname=postgres
debezium.source.database.port=5432
debezium.source.database.user=keycloak
debezium.source.database.password=keycloak
debezium.source.database.dbname=keycloak
debezium.source.topic.prefix=keycloak

debezium.source.plugin.name=pgoutput
debezium.source.slot.name=debezium
debezium.source.publication.autocreate.mode=filtered

debezium.source.offset.storage.file.filename=/debezium/data/offsets.dat

debezium.source.table.include.list=public.user_entity

debezium.sink.type=kafka
debezium.sink.kafka.producer.bootstrap.servers=redpanda:9092
debezium.sink.kafka.producer.key.serializer=org.apache.kafka.common.serialization.StringSerializer
debezium.sink.kafka.producer.value.serializer=org.apache.kafka.common.serialization.StringSerializer

debezium.format.value=json
debezium.format.key=json
debezium.format.value.schemas.enable=false
debezium.format.key.schemas.enable=false


# -------- TRANSFORMS --------

debezium.transforms=unwrap,keepFields

# 1. Flatten the Debezium envelope and expose __op field
debezium.transforms.unwrap.type=io.debezium.transforms.ExtractNewRecordState
debezium.transforms.unwrap.delete.handling.mode=rewrite
debezium.transforms.unwrap.drop.tombstones=true
debezium.transforms.unwrap.add.fields=op

# 2. Keep only relevant fields: id, username, email, __op
debezium.transforms.keepFields.type=org.apache.kafka.connect.transforms.ReplaceField$Value
debezium.transforms.keepFields.include=id,username,email,enabled,__op
